# This is a basic workflow to help you get started with Actions

name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Date
        run: |
          date
      - name: ls -l
        run: |
          ls -l
          
          
